import subprocess, os, sys

# Try win32com for Outlook
try:
    import win32com.client as win32
    outlook = win32.Dispatch('outlook.application')
    mail = outlook.CreateItem(0)

    mail.To = "leahliu@culines.com"
    mail.Subject = "[Claw] Alphaliner Intelligence Digest - Week 21 2026"

    report_path = r"C:\Users\culadmin\Claw-Report\reports\alphaliner-digest.html"
    github_url = "https://leahliul.github.io/Claw-Report/reports/alphaliner-digest.html"

    mail.HTMLBody = f"""
<html>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Microsoft YaHei', sans-serif; background: #f6f8fa; padding: 20px;">
<div style="max-width: 680px; margin: 0 auto; background: #ffffff; border-radius: 8px; border: 1px solid #d0d7de; overflow: hidden;">

  <div style="background: linear-gradient(135deg, #0d1117, #161b22); padding: 24px; border-bottom: 3px solid #58a6ff;">
    <div style="display: flex; align-items: center; gap: 12px;">
      <div style="background: linear-gradient(135deg, #1f6feb, #58a6ff); border-radius: 8px; width: 40px; height: 40px; display: inline-flex; align-items: center; justify-content: center; font-size: 20px;">🚢</div>
      <div>
        <h1 style="color: #e6edf3; font-size: 18px; margin: 0; font-weight: 800;">CUL — Alphaliner Intelligence Digest</h1>
        <p style="color: #8b949e; font-size: 12px; margin: 4px 0 0;">Week 21, 2026 (May 12–18) · Auto-generated by Claw</p>
      </div>
    </div>
  </div>

  <div style="padding: 24px;">
    <div style="background: #fff3cd; border: 1px solid #ffc107; border-radius: 8px; padding: 12px 16px; margin-bottom: 20px;">
      <strong style="color: #856404;">⚡ 本周重点：运价骤升 + 双重断裂风险持续</strong><br>
      <span style="font-size: 13px; color: #533f03;">Drewry WCI +12% 至 $2,553/FEU（2026年单周最大涨幅），SCFI 突破 2,000 关口至 2,140.66。红海+霍尔木兹双重绕航合计吸收约 10-12% 全球运力。</span>
    </div>

    <h2 style="font-size: 15px; color: #24292f; border-bottom: 1px solid #d0d7de; padding-bottom: 8px; margin-bottom: 16px;">📰 本周要闻 (Week 21, May 12–18, 2026)</h2>

    <table style="width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 20px;">
      <tr style="background: #f6f8fa;">
        <th style="padding: 8px 12px; text-align: left; color: #57606a; border-bottom: 1px solid #d0d7de; font-weight: 600;">#</th>
        <th style="padding: 8px 12px; text-align: left; color: #57606a; border-bottom: 1px solid #d0d7de; font-weight: 600;">标题</th>
        <th style="padding: 8px 12px; text-align: left; color: #57606a; border-bottom: 1px solid #d0d7de; font-weight: 600;">部门相关</th>
      </tr>
      <tr>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef; color: #cf222e; font-weight: 700;">⭐</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><strong>Drewry WCI +12% 至 $2,553/FEU — 2026年最大单周涨幅</strong></td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><span style="background:#1a2f45;color:#58a6ff;border-radius:4px;padding:2px 6px;font-size:11px;">财务</span> <span style="background:#0d4429;color:#3fb950;border-radius:4px;padding:2px 6px;font-size:11px;">商务</span></td>
      </tr>
      <tr style="background:#f6f8fa;">
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef; color: #cf222e; font-weight: 700;">⭐</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><strong>SCFI 突破 2,000 至 2,140.66（关税缓和前装货潮）</strong></td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><span style="background:#1a2f45;color:#58a6ff;border-radius:4px;padding:2px 6px;font-size:11px;">财务</span> <span style="background:#0d4429;color:#3fb950;border-radius:4px;padding:2px 6px;font-size:11px;">运营</span></td>
      </tr>
      <tr>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">3</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">霍尔木兹海峡实质封锁 — Operation Epic Fury 后持续关闭</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><span style="background:#0d4429;color:#3fb950;border-radius:4px;padding:2px 6px;font-size:11px;">运营</span> <span style="background:#2d1b4e;color:#bc8cff;border-radius:4px;padding:2px 6px;font-size:11px;">法务</span></td>
      </tr>
      <tr style="background:#f6f8fa;">
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">4</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">MSC 达成 1,000 艘里程碑 — 全球首家</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><span style="background:#0f3240;color:#39d353;border-radius:4px;padding:2px 6px;font-size:11px;">航线</span></td>
      </tr>
      <tr>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">5</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">空白航次 30 班取消（Wk21-25），占东西向 4.3%</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><span style="background:#0d4429;color:#3fb950;border-radius:4px;padding:2px 6px;font-size:11px;">运营</span></td>
      </tr>
      <tr style="background:#f6f8fa;">
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">6</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">青岛港拥堵约 4 天延误（关税缓和前装货潮）</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><span style="background:#0d4429;color:#3fb950;border-radius:4px;padding:2px 6px;font-size:11px;">运营</span> <span style="background:#3d2700;color:#e3b341;border-radius:4px;padding:2px 6px;font-size:11px;">设备</span></td>
      </tr>
      <tr>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">7</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">中美关税 90 天缓和窗口（4月22日—7月中旬），均值 ~33%</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><span style="background:#1a2f45;color:#58a6ff;border-radius:4px;padding:2px 6px;font-size:11px;">财务</span> <span style="background:#0d4429;color:#3fb950;border-radius:4px;padding:2px 6px;font-size:11px;">商务</span></td>
      </tr>
    </table>

    <h2 style="font-size: 15px; color: #24292f; border-bottom: 1px solid #d0d7de; padding-bottom: 8px; margin-bottom: 16px;">📊 市场数据快览 (May 14–15, 2026)</h2>

    <table style="width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 20px;">
      <tr style="background: #f6f8fa;">
        <th style="padding: 8px 12px; text-align: left; color: #57606a; border-bottom: 1px solid #d0d7de; font-weight: 600;">指标</th>
        <th style="padding: 8px 12px; text-align: right; color: #57606a; border-bottom: 1px solid #d0d7de; font-weight: 600;">数值</th>
        <th style="padding: 8px 12px; text-align: right; color: #57606a; border-bottom: 1px solid #d0d7de; font-weight: 600;">周环比</th>
      </tr>
      <tr>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">Drewry WCI 综合</td>
        <td style="padding: 8px 12px; text-align: right; border-bottom: 1px solid #eaecef; font-weight: 700;">$2,553/40ft</td>
        <td style="padding: 8px 12px; text-align: right; border-bottom: 1px solid #eaecef; color: #cf222e; font-weight: 600;">▲ +12%</td>
      </tr>
      <tr style="background:#f6f8fa;">
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">SCFI 综合指数</td>
        <td style="padding: 8px 12px; text-align: right; border-bottom: 1px solid #eaecef; font-weight: 700;">2,140.66</td>
        <td style="padding: 8px 12px; text-align: right; border-bottom: 1px solid #eaecef; color: #cf222e; font-weight: 600;">▲ +186.45</td>
      </tr>
      <tr>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">CCFI 综合指数</td>
        <td style="padding: 8px 12px; text-align: right; border-bottom: 1px solid #eaecef; font-weight: 700;">1,280.46</td>
        <td style="padding: 8px 12px; text-align: right; border-bottom: 1px solid #eaecef; color: #cf222e; font-weight: 600;">▲ +0.1%</td>
      </tr>
      <tr style="background:#f6f8fa;">
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">TPEB (美西) 估算</td>
        <td style="padding: 8px 12px; text-align: right; border-bottom: 1px solid #eaecef; font-weight: 700;">~$3,800/FEU</td>
        <td style="padding: 8px 12px; text-align: right; border-bottom: 1px solid #eaecef; color: #cf222e; font-weight: 600;">▲ 急升</td>
      </tr>
      <tr>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">全球运力压缩（绕航）</td>
        <td style="padding: 8px 12px; text-align: right; border-bottom: 1px solid #eaecef; font-weight: 700;">~10-12%</td>
        <td style="padding: 8px 12px; text-align: right; border-bottom: 1px solid #eaecef; color: #8b949e;">红海+霍尔木兹</td>
      </tr>
    </table>

    <div style="text-align: center; margin: 24px 0;">
      <a href="{github_url}" style="background: linear-gradient(135deg, #1f6feb, #58a6ff); color: #ffffff; text-decoration: none; padding: 12px 28px; border-radius: 6px; font-weight: 700; font-size: 14px; display: inline-block;">
        &#x1F4CA; 查看完整互动报告（GitHub Pages）
      </a>
    </div>
  </div>

  <div style="background: #f6f8fa; padding: 16px 24px; border-top: 1px solid #d0d7de; text-align: center; font-size: 11px; color: #57606a;">
    <p>CUL — Alphaliner Intelligence Digest | Week 21, 2026 | 内部使用 · AI辅助分析 · 数据来源于公开信息</p>
    <p style="margin-top: 4px;">Generated by Claw Automation · {github_url}</p>
  </div>
</div>
</body>
</html>
"""

    # Attach the HTML report
    mail.Attachments.Add(report_path)

    mail.Send()
    print("EMAIL_SENT_SUCCESS")

except ImportError:
    print("WIN32COM_NOT_AVAILABLE")
except Exception as e:
    print(f"EMAIL_ERROR: {e}")
