"""Send email notification for Alphaliner Digest Week 22 2026."""
import win32com.client as win32
import pythoncom

pythoncom.CoInitialize()

outlook = win32.Dispatch('Outlook.Application')
mail = outlook.CreateItem(0)

mail.To = "leahliu@culines.com"
mail.Subject = "[Claw] Alphaliner Digest 已更新 - Week 22 (2026-05-19~25)"

github_url = "https://leahliul.github.io/Claw-Report/reports/alphaliner-digest.html"

mail.HTMLBody = f"""
<html>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Microsoft YaHei', sans-serif; background: #f6f8fa; padding: 20px;">
<div style="max-width: 680px; margin: 0 auto; background: #ffffff; border-radius: 8px; border: 1px solid #d0d7de; overflow: hidden;">

  <div style="background: linear-gradient(135deg, #0d1117, #161b22); padding: 24px; border-bottom: 3px solid #58a6ff;">
    <div style="display: flex; align-items: center; gap: 12px;">
      <div style="background: linear-gradient(135deg, #1f6feb, #58a6ff); border-radius: 8px; width: 40px; height: 40px; display: inline-flex; align-items: center; justify-content: center; font-size: 20px;">🚢</div>
      <div>
        <h1 style="color: #e6edf3; font-size: 18px; margin: 0; font-weight: 800;">CUL — Alphaliner Intelligence Digest</h1>
        <p style="color: #8b949e; font-size: 12px; margin: 4px 0 0;">Week 22, 2026 (May 19–25) · Auto-generated by Claw</p>
      </div>
    </div>
  </div>

  <div style="padding: 24px;">
    <div style="background: #fff3cd; border: 1px solid #ffc107; border-radius: 8px; padding: 12px 16px; margin-bottom: 20px;">
      <strong style="color: #856404;">⚡ 本周重点：旺季提前引爆 · SCFI三连涨 · MSC突破500万TEU</strong><br>
      <span style="font-size: 13px; color: #533f03;">SCFI综合2,218.15点(+3.6%)，Drewry WCI $2,712/FEU(+6%)。头部船司集中空班压缩6月运力至26万TEU/周。MSC成为全球首家突破500万TEU班轮公司，占全球运力18.7%。</span>
    </div>

    <h2 style="font-size: 15px; color: #24292f; border-bottom: 1px solid #d0d7de; padding-bottom: 8px; margin-bottom: 16px;">📰 本周要闻 (Week 22, May 19–25, 2026)</h2>

    <table style="width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 20px;">
      <tr style="background: #f6f8fa;">
        <th style="padding: 8px 12px; text-align: left; color: #57606a; border-bottom: 1px solid #d0d7de; font-weight: 600; width:32px">#</th>
        <th style="padding: 8px 12px; text-align: left; color: #57606a; border-bottom: 1px solid #d0d7de; font-weight: 600;">标题</th>
        <th style="padding: 8px 12px; text-align: left; color: #57606a; border-bottom: 1px solid #d0d7de; font-weight: 600; width:120px">标签</th>
      </tr>
      <tr>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef; color: #cf222e; font-weight: 700;">⭐</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><strong>SCFI三连涨至2,218 · Drewry WCI +6%至$2,712/FEU</strong></td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><span style="background:#1a2f45;color:#58a6ff;border-radius:4px;padding:2px 6px;font-size:11px;">EQ运价</span></td>
      </tr>
      <tr style="background:#f6f8fa;">
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef; color: #cf222e; font-weight: 700;">⭐</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><strong>MSC突破500万TEU — 全球班轮史上首例</strong></td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><span style="background:#1a2a3a;color:#79c0ff;border-radius:4px;padding:2px 6px;font-size:11px;">VSL船舶</span></td>
      </tr>
      <tr>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef; color: #0969da; font-weight: 700;">▸</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">头部船司6月集中空班 — 单周运力削减至26万TEU</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><span style="background:#0d4429;color:#3fb950;border-radius:4px;padding:2px 6px;font-size:11px;">OPS运营</span></td>
      </tr>
      <tr style="background:#f6f8fa;">
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef; color: #0969da; font-weight: 700;">▸</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">"一舱难求"再现 — 欧美线爆舱 · 旺季提前启动</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><span style="background:#3d1515;color:#f85149;border-radius:4px;padding:2px 6px;font-size:11px;">TRD贸易</span></td>
      </tr>
      <tr>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef; color: #0969da; font-weight: 700;">▸</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">波斯湾运价$4,306/TEU (+4.2%) — 中东绕航溢价持续</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><span style="background:#1a2f45;color:#58a6ff;border-radius:4px;padding:2px 6px;font-size:11px;">EQ运价</span> <span style="background:#0d4429;color:#3fb950;border-radius:4px;padding:2px 6px;font-size:11px;">★CUL</span></td>
      </tr>
      <tr style="background:#f6f8fa;">
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef; color: #0969da; font-weight: 700;">▸</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;">中远海运新增新加坡-哥打京那巴鲁KTS4航线（5月3日起）</td>
        <td style="padding: 8px 12px; border-bottom: 1px solid #eaecef;"><span style="background:#0f3240;color:#39d353;border-radius:4px;padding:2px 6px;font-size:11px;">NET航网</span> <span style="background:#0d4429;color:#3fb950;border-radius:4px;padding:2px 6px;font-size:11px;">★CUL</span></td>
      </tr>
    </table>

    <div style="background: #0d1117; border-radius: 8px; padding: 16px; margin-bottom: 20px;">
      <p style="color: #8b949e; font-size: 12px; margin: 0 0 12px;">📊 运价速览（2026-05-22）</p>
      <table style="width:100%; border-collapse:collapse; font-size:13px; color:#e6edf3;">
        <tr>
          <td style="padding:4px 8px; color:#8b949e;">SCFI综合</td>
          <td style="padding:4px 8px; font-weight:700; color:#58a6ff;">2,218.15</td>
          <td style="padding:4px 8px; color:#f85149;">▲ 3.6%</td>
        </tr>
        <tr>
          <td style="padding:4px 8px; color:#8b949e;">Drewry WCI</td>
          <td style="padding:4px 8px; font-weight:700; color:#58a6ff;">$2,712/FEU</td>
          <td style="padding:4px 8px; color:#f85149;">▲ 6%</td>
        </tr>
        <tr>
          <td style="padding:4px 8px; color:#8b949e;">欧洲运价</td>
          <td style="padding:4px 8px; font-weight:700; color:#58a6ff;">$1,905/TEU</td>
          <td style="padding:4px 8px; color:#f85149;">▲ 4.9%</td>
        </tr>
        <tr>
          <td style="padding:4px 8px; color:#8b949e;">美西运价</td>
          <td style="padding:4px 8px; font-weight:700; color:#58a6ff;">$3,154/FEU</td>
          <td style="padding:4px 8px; color:#f85149;">▲ 1.2%</td>
        </tr>
        <tr>
          <td style="padding:4px 8px; color:#8b949e; font-weight:700;">波斯湾（★CUL）</td>
          <td style="padding:4px 8px; font-weight:700; color:#3fb950;">$4,306/TEU</td>
          <td style="padding:4px 8px; color:#f85149;">▲ 4.2%</td>
        </tr>
      </table>
    </div>

    <div style="text-align: center; margin: 20px 0;">
      <a href="{github_url}" style="background: #1f6feb; color: #fff; padding: 10px 24px; border-radius: 6px; font-size: 14px; font-weight: 600; text-decoration: none; display: inline-block;">📄 查看完整报告 →</a>
    </div>

    <p style="font-size: 11px; color: #8b949e; border-top: 1px solid #d0d7de; padding-top: 12px; margin-top: 12px;">
      ⚠ AI解读仅供参考，不构成商业决策依据。数据来源：Alphaliner Weekly、上海航运交易所SCFI、Drewry WCI、Linerlytica、财联社。<br>
      Generated by Claw · {github_url}
    </p>
  </div>
</div>
</body>
</html>
"""

mail.Send()
print("EMAIL_SENT_OK")
